# This manifest creates a Namespace to be used by the sample-apiserver, a ServiceAccount and
# ConfigMap and Secret for storing TLS certificates for etcd-proxy.
---
# Namespace where the API server and all related resources are deployed.
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-sample-apiserver
---
# ServiceAccount to be used by the sample-apiserver.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: apiserver
  namespace: k8s-sample-apiserver
---
# ConfigMap used to store the serving CA certificate for verifying the etcd-proxy identity.
# This ConfigMap is specified in the EtcdStorage Spec.
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-serving-ca
  namespace: k8s-sample-apiserver
data:
---
# Secret for storing the client certificate/key pair used to access the etcd proxy.
# This Secret is specified in the EtcdStorage Spec.
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-cert
  namespace: k8s-sample-apiserver
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""

