apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdstorages.etcd.xmudrii.com
spec:
  group: etcd.xmudrii.com
  version: v1alpha1
  names:
    kind: EtcdStorage
    plural: etcdstorages
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              maxLength: 59 # because of service name, explained above.
        spec:
          required: ["signingCertificateValidity", "servingCertificateValidity", "clientCertificateValidity"]
          properties:
            caCertConfigMap:
              type: array
              items:
                type: object
                required: ["name", "namespace"]
                properties:
                  name:
                    type: string
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                  namespace:
                    type: string
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
            clientCertSecret:
              type: array
              items:
                type: object
                required: ["name", "namespace"]
                properties:
                  name:
                    type: string
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                  namespace:
                    type: string
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
            signingCertificateValidity:
              type: string
              pattern: '^[0-9]*[.]?[0-9]*(ns|us|ms|m|s|h)$'
            servingCertificateValidity:
              type: string
              pattern: '^[0-9]*[.]?[0-9]*(ns|us|ms|m|s|h)'
            clientCertificateValidity:
              type: string
              pattern: '^[0-9]*[.]?[0-9]*(ns|us|ms|m|s|h)'

