apiVersion: etcd.xmudrii.com/v1alpha1
kind: EtcdStorage
metadata:
  name: sample-apiserver # the name of the EtcdStorage resource is also the name of etcd namespace. As we’re building the service’s name based of this name, the name cannot be longer than 64-5 character (because we’re using ‘etcd-’ prefix in service’s name). The name must consist only of lower-case characters, ‘-’ and ‘.’.
spec:
  caCertConfigMap:
  - name: etcd-serving-ca
    namespace: k8s-sample-apiserver
  clientCertSecret: # Client certificate for accessing etcdproxy. Stored in Secrets specified by namespace/name pairs below. Secrets along with RBAC rules allowing EtcdProxyController to access specified Secrets must exist prior to creating an ‘EtcdStorage’ instance.
  - name: etcd-client-cert
    namespace: k8s-sample-apiserver
