# Certificates used by the EtcdProxy Controller to access the core etcd.
# Supposed to be deployed in the EtcdProxy Controller namespace (kube-apiserver-storage).
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-coreserving-ca
  namespace: kube-apiserver-storage
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB5DCCAYqgAwIBAgIUJJ9xZX5JIg6Wb9ve9N7xUOAcx54wCgYIKoZIzj0EAwIw
    UDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNp
    c2NvMRwwGgYDVQQDExNldGNkLXN2Yy0xLmV0Y2Quc3ZjMB4XDTE4MDYxNzIwMDYw
    MFoXDTIzMDYxNjIwMDYwMFowUDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYw
    FAYDVQQHEw1TYW4gRnJhbmNpc2NvMRwwGgYDVQQDExNldGNkLXN2Yy0xLmV0Y2Qu
    c3ZjMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbVcB33hMNP1G0T5E65YdEiZ1
    wsyEJXfn94dL4/O1vNjfRiImuNwN5gJPy8baG444osb1yfH5asxTIAzvtQalaKNC
    MEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKtG
    dEHYxzQhgNM9PNStm8BB+ON5MAoGCCqGSM49BAMCA0gAMEUCIQDA8DX3tSU5jeuD
    E6WVeDCbXZfTiCuUMgAlcM8GXDTV5QIgN0ZgOL7hS7XAMwhTVUbhuKWi+IRZi3wL
    +r9bAo3ITMg=
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-coreserving-cert
  namespace: kube-apiserver-storage
type: Opaque
data:
  client.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDekNDQWJDZ0F3SUJBZ0lVS0FWdmcrRkRUQzNQUzI5MXd3WncvZ2pVWWwwd0NnWUlLb1pJemowRUF3SXcKVURFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ1RBa05CTVJZd0ZBWURWUVFIRXcxVFlXNGdSbkpoYm1OcApjMk52TVJ3d0dnWURWUVFERXhObGRHTmtMWE4yWXkweExtVjBZMlF1YzNaak1CNFhEVEU0TURZeE56SXdNRGN3Ck1Gb1hEVEl6TURZeE5qSXdNRGN3TUZvd1F6RUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdUQWtOQk1SWXcKRkFZRFZRUUhFdzFUWVc0Z1JuSmhibU5wYzJOdk1ROHdEUVlEVlFRREV3WmpiR2xsYm5Rd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUkNmUThCQXdFNklBZk9tMkZyWHdkVTY5ZHBTME5qdGZrSU9nbGc4RzhWCnBWMnY5d25lWXl3RWhQUkJlN1IwVXFVOGljR1YwckFCQkZVUXBQWkNJaVUvbzNVd2N6QU9CZ05WSFE4QkFmOEUKQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RQpGZ1FVaWF0Q3dVYk8rOWM3MklEWWhXQ0FYMVIzc3pvd0h3WURWUjBqQkJnd0ZvQVVxMFowUWRqSE5DR0EwejA4CjFLMmJ3RUg0NDNrd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFJZ21UQlJKWmVoNmw5RGY0SkN0Q213RndrZGEKMmZYSXRvcnZrdm9weUxrZ0FpRUE5ak51N3ZkS2djR0ZmTTNtMWpTc1Fkb01jdm5pUlQybnkvWHJlcHRCek5nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  client-key.pem: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxMc2Y0aytuSTRjeG5wK0Mzc0NhQ0p4Vmt6M2dkZzZWbk1YdGRVZU1OWmpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUW4wUEFRTUJPaUFIenB0aGExOEhWT3ZYYVV0RFk3WDVDRG9KWVBCdkZhVmRyL2NKM21NcwpCSVQwUVh1MGRGS2xQSW5CbGRLd0FRUlZFS1QyUWlJbFB3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=