apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdstorages.etcd.xmudrii.com
spec:
  group: etcd.xmudrii.com
  version: v1alpha1
  names:
    kind: EtcdStorage
    plural: etcdstorages
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              maxLength: 59 # because of service name, explained above.
