apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: etcdproxy
  labels:
    controller: epc
spec:
  replicas: 1
  selector:
    matchLabels:
        controller: epc
  template:
    metadata:
      labels:
        controller: epc
    spec:
      containers:
      - name: etcdproxy
        image: quay.io/coreos/etcd:v3.2.18
        command: ["/usr/local/bin/etcd", "grpc-proxy", "start"]
        args: ["--endpoints=http://etcd-svc-1.etcd.svc.cluster.local:2379", "--namespace=/exp", "--listen-addr=0.0.0.0:2379"]
