apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: etcdproxy
spec:
  replicas: 1
  selector:
    matchLabels:
        controller: epc
  template:
    metadata:
      labels:
        controller: epc
    spec:
      containers:
      - name: etcdproxy
        image: quay.io/coreos/etcd:v3.2.18
        command: ["/usr/local/bin/etcd", "grpc-proxy", "start"]
        args: ["--endpoints=https://etcd-svc-1.etcd.svc:2379", "--namespace=/example", "--listen-addr=0.0.0.0:2379", "--cacert=/etc/certs/ca.pem", "--cert=/etc/certs/client.pem", "--key=/etc/certs/client-key.pem"]
        volumeMounts:
        - name: client-certs
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: client-certs
        secret:
          secretName: client-certs
